[package]
name = "secp256k1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ibig = "0.3.6"
lazy_static = "1.4.0"
num-traits = "0.2.18"

[profile.release]
debug = true