[package]
name = "bt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static-rc = "0.6.1"

[profile.release]
debug = true
