[package]
name = "edigits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
ibig = "0.3.6"
num-bigint = "0.4.4"
